### ISSUE TITLE
Any chance to replace default "list" with a "nestable_tree"?

### ISSUE THREAD

**Issue by brykov** [dalpo/rails_admin_nestable#48]
As far as I can judge, the interface provided by "nestable_tree" action can be used instead of default "list" action.

How can I replace the "list" with "nestable_tree"?

**Comment by newstler** [comment]
+1

**Comment by dalpo** [comment]
Hi @brykov and @newstler :)

I think you could remove the `list` action from rails_admin configuration and replace it with the `nestable_list`/`nestable_tree` custom action.

For instance:

```

  config.actions do
    dashboard                     # mandatory
    # index                             # mandatory
    nestable                           # rails_admin_nestable actions
    new do
      except %w(Course)
    end
    export
    bulk_delete do
      except %w(Course)
    end
    show
    clone do
      except %w(Course)
    end
    edit
    delete do
      except %w(Course)
    end
    show_in_app


    ## With an audit adapter, you can add:
    # history_index
    # history_show
  end
```

**Comment by newstler** [comment]
Thanx, @dalpo!
I just made like this:
```
  config.actions do
    dashboard                     # mandatory
    index do
      except %w(Category)
    end                         # mandatory
    nestable
    new
    export
    bulk_delete
    show
    edit
    delete
    show_in_app

    ## With an audit adapter, you can add:
    # history_index
    # history_show

  end
```
But this way `Category` disappears from the menu :(

**Comment by newstler** [comment]
And your way I got totally blank menu

**Comment by dalpo** [comment]
Uhm.. the index action seems to be hardcoded into the all rails_admin codebase.
Take a look here: https://github.com/sferik/rails_admin/search?utf8=%E2%9C%93&q=index_path

I'm sorry but there isn't a simple way to get rails_admin_nestable as the default index action
