### ISSUE TITLE
nestable list not nestable

### ISSUE THREAD

**Issue by ain** [dalpo/rails_admin_nestable#58]
__Steps to reproduce__:

1. Add `nestable_list` configuration to `initializers/rails_admin.rb`:
  
  ```ruby
  config.model ModelName do
    nestable_list true
  end
  ```
2. Add migration:

  ```ruby
  class AddPositionToModelName < ActiveRecord::Migration
    def change
      add_column :model_name, :position, :string, index: true
    end
  end
  ```
3. Create 3 ModelName items in Rails Admin
3. Access Sorting tab
4. Try to drag one item into the other

__What happens__:  items can not be nested.

__What should happen__: if the list is nestable, it should be possible to drag one item into another.

```
Safari 9.1.2 (11601.7.7)
rails 4.2.6
ruby 2.3.1
rails_admin eefa8ac (latest master)
rails_admin_nestable 0.3.2
```

**Comment by ain** [comment]
I think it is just a naming issue, `nestable_tree` works brilliantly.

Great work!

**Comment by dalpo** [comment]
Thanks :) And yes.. I should rewrite the readme.

rails_admin_nestable allow you to choose between two possible configurations:

1.The  `nestable_list` for sorting simple list of records.
2. The `nestable_tree` to organize records into a tree structure.

Pay attention that if you need  the `nestable_tree` scenario, with this gem you should to setup the `ancestry` gem for your model to provide some internal model methods.

Take a look here for more info:  https://github.com/stefankroes/ancestry

**Comment by ain** [comment]
Yup, thanks. It's working nicely with `ancestry`. So the platform I listed above is confirmed to work :)
