### ISSUE TITLE
Gets stuck in loop

### ISSUE THREAD

**Issue by thisislorne** [dalpo/rails_admin_nestable#59]
Hey!

Using the following: 
```
gem 'ancestry'
gem 'rails_admin', '~> 1.1.1'
gem 'rails_admin_nestable', '~> 0.3.2'
```

After loading and making changes, I'm getting stuck in a loop of the following:

```
actionview (5.0.1) lib/action_view/helpers/capture_helper.rb:39:in `block in capture'
actionview (5.0.1) lib/action_view/helpers/capture_helper.rb:203:in `with_output_buffer'
haml (4.0.7) lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
actionview (5.0.1) lib/action_view/helpers/capture_helper.rb:39:in `capture'
haml (4.0.7) lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
actionview (5.0.1) lib/action_view/helpers/tag_helper.rb:107:in `content_tag'
haml (4.0.7) lib/haml/helpers/action_view_mods.rb:69:in `content_tag_with_haml'
rails_admin_nestable (0.3.2) lib/rails_admin_nestable/helper.rb:7:in `block in nested_tree_nodes'
rails_admin_nestable (0.3.2) lib/rails_admin_nestable/helper.rb:4:in `each'
rails_admin_nestable (0.3.2) lib/rails_admin_nestable/helper.rb:4:in `map'
rails_admin_nestable (0.3.2) lib/rails_admin_nestable/helper.rb:4:in `nested_tree_nodes'
rails_admin_nestable (0.3.2) lib/rails_admin_nestable/helper.rb:15:in `block (2 levels) in nested_tree_nodes'
```

Config looks like:
```
...
config.model Page do
    nestable_tree({
      position_field: :ancestry,
      max_depth: 3
    })
  end
```

and
```

class Page < ApplicationRecord
    has_ancestry 
    ...
end
```

The values that end up in the ancestry col are just integers ( ancestry: "2" ) whereas my understanding is they should look more like paths  ( ancestry: "1/2" ).

**Comment by dalpo** [comment]
Hi @thisislorne!
Could you try to remove the `position_field: :ancestry` option and see if it works?
You shouldn't use the `ancestry` column as `position_field`.

The option `position_field` is only responsible for sorting the node's tree siblings and on the other side the column `ancestry` is used by the ancestry gem to manage the "deepness" of a node/record into a tree.
So, eventually, you could create another numeric column (for example: "position") to manage the sorting for node's tree siblings.

Let me know if it works :wink:
